WAL:
    segmentSize: 512
MemTable:
    maxSize: 1024
    structure: SkipList
    instances: 1
BTree:
    minSize: 3
SSTable:
    savePath: ./data
    singleFile: false
    summaryDegree: 5
    indexDegree: 5
    compression: false
    filterPrecision: 0.01
    merkleTreeChunkSize: 1024
LSMTree:
    maxLevel: 4
Cache:
    maxSize: 1024

