WAL:
    segmentSize: 32768
    bufferSize: 8
MemTable:
    maxSize: 1024
    structure: SkipList
    instances: 1
    BTree:
        minSize: 16
    SkipList:
        maxHeight: 32
SSTable:
    savePath: ./data
    singleFile: false
    summaryDegree: 5
    indexDegree: 5
    compression: false
    filterPrecision: 0.01
LSMTree:
    maxLevel: 4
Cache:
    maxSize: 1024
