WAL:
    segmentSize: 32768
    bufferSize: 8
    walFolderPath: ./wal
Memtable:
    maxSize: 1024
    structure: SkipList # SkipList, HashMap, BTree
    instances: 1
    BTree:
        minSize: 16
    SkipList:
        maxHeight: 32
SSTable:
    savePath: ./data
    singleFile: false
    summaryDegree: 5
    indexDegree: 5
    compression: true
    filterPrecision: 0.01
    merkleTreeChunkSize: 1024
LSMTree:
    maxLevel: 4
    compactionAlgorithm: Size-Tiered # Size-Tiered, Leveled
    maxLsmNodesPerLevel: 8
Cache:
    maxSize: 1024
TokenBucket:
    maxTokenSize: 1024
    interval: 60